/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.brasil.catracaacademia.graphic;

import com.estruturadados.catracaacademia.database.model.MatriculaPlano;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DadosMatriculaModalidadeView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DadosMatriculaModalidade
     */
    
    List<MatriculaPlano> listaMatriculaPlano;
    
    public DadosMatriculaModalidadeView(List<MatriculaPlano> listaMatriculaPlano) {
        initComponents();
        this.listaMatriculaPlano = listaMatriculaPlano;        
        
        if(this.listaMatriculaPlano != null){
            preencherDados(this.listaMatriculaPlano);
        }
    }
    
    public void preencherDados(List<MatriculaPlano> list){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldNomeAluno.setText(list.get(0).getMatricula().getAluno().getNome());
        jTextFieldDescricaoPlano.setText(list.get(0).getPlano().getDescricao());
        jTextFieldDataMatricula.setText(sdf.format(list.get(0).getMatricula().getDataMatricula()));
        jTextFieldDataInicio.setText(sdf.format(list.get(0).getDataInicio()));
        
        DefaultTableModel table = (DefaultTableModel) jTableModalidadesGraduacao.getModel();
        table.setRowCount(0);
        for(MatriculaPlano mp : list){
           Object[] dados = {mp.getPlano().getGraduacao().getModalidade().getNome(), mp.getPlano().getGraduacao().getNome()};
           table.addRow(dados);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDadosMatriculasModalidades = new javax.swing.JPanel();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jTextFieldDataMatricula = new javax.swing.JTextField();
        jTextFieldDescricaoPlano = new javax.swing.JTextField();
        jLabelDataMatricula = new javax.swing.JLabel();
        jLabelDataInicio = new javax.swing.JLabel();
        jTextFieldDataInicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModalidadesGraduacao = new javax.swing.JTable();

        setClosable(true);
        setTitle("Matricula");
        setToolTipText("");

        jPanelDadosMatriculasModalidades.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jTextFieldNomeAluno.setEditable(false);
        jTextFieldNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeAlunoActionPerformed(evt);
            }
        });

        jTextFieldDataMatricula.setEditable(false);

        jTextFieldDescricaoPlano.setEditable(false);

        jLabelDataMatricula.setText("Data matrícula:");

        jLabelDataInicio.setText("Data início:");

        jTextFieldDataInicio.setEditable(false);

        javax.swing.GroupLayout jPanelDadosMatriculasModalidadesLayout = new javax.swing.GroupLayout(jPanelDadosMatriculasModalidades);
        jPanelDadosMatriculasModalidades.setLayout(jPanelDadosMatriculasModalidadesLayout);
        jPanelDadosMatriculasModalidadesLayout.setHorizontalGroup(
            jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosMatriculasModalidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosMatriculasModalidadesLayout.createSequentialGroup()
                        .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDescricaoPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(jPanelDadosMatriculasModalidadesLayout.createSequentialGroup()
                        .addGroup(jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosMatriculasModalidadesLayout.createSequentialGroup()
                                .addComponent(jLabelDataMatricula)
                                .addGap(47, 47, 47)
                                .addComponent(jLabelDataInicio))
                            .addGroup(jPanelDadosMatriculasModalidadesLayout.createSequentialGroup()
                                .addComponent(jTextFieldDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDadosMatriculasModalidadesLayout.setVerticalGroup(
            jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosMatriculasModalidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDescricaoPlano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataMatricula)
                    .addComponent(jLabelDataInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosMatriculasModalidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableModalidadesGraduacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modalidade", "Graduação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableModalidadesGraduacao);
        if (jTableModalidadesGraduacao.getColumnModel().getColumnCount() > 0) {
            jTableModalidadesGraduacao.getColumnModel().getColumn(0).setResizable(false);
            jTableModalidadesGraduacao.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDadosMatriculasModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosMatriculasModalidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDataInicio;
    private javax.swing.JLabel jLabelDataMatricula;
    private javax.swing.JPanel jPanelDadosMatriculasModalidades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModalidadesGraduacao;
    private javax.swing.JTextField jTextFieldDataInicio;
    private javax.swing.JTextField jTextFieldDataMatricula;
    private javax.swing.JTextField jTextFieldDescricaoPlano;
    private javax.swing.JTextField jTextFieldNomeAluno;
    // End of variables declaration//GEN-END:variables
}
