/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.brasil.catracaacademia.graphic;

import com.estruturadados.catracaacademia.database.model.Aluno;
import java.text.SimpleDateFormat;

/**
 *
 * @author User
 */
public class DadosAlunoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DadosAlunoView
     */
    private Aluno aluno;
    
    public DadosAlunoView(Aluno aluno) {
        initComponents();
        this.aluno = aluno;
        
        preencherDados(this.aluno);
    }
    
    private void preencherDados(Aluno aluno) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldCodigoAluno.setText(Integer.toString(aluno.getCodigo()));
        jTextFieldNomeAluno.setText(aluno.getNome());
        jTextFieldCPF.setText(aluno.getCpf());
        jTextFieldDataNascimento.setText(sdf.format(aluno.getData_nascimento()));
        jTextFieldContato.setText(aluno.getContato());
        jTextFieldCodigoCidade.setText(Integer.toString(aluno.getCidade().getCodigo()));
        jTextFieldNomeCidade.setText(aluno.getCidade().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDadosAluno = new javax.swing.JPanel();
        jTextFieldCodigoAluno = new javax.swing.JTextField();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldContato = new javax.swing.JTextField();
        jTextFieldCodigoCidade = new javax.swing.JTextField();
        jTextFieldNomeCidade = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Aluno");

        jPanelDadosAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Aluno"));

        jTextFieldCodigoAluno.setEditable(false);

        jTextFieldNomeAluno.setEditable(false);

        jTextFieldDataNascimento.setEditable(false);

        jTextFieldCPF.setEditable(false);

        jTextFieldContato.setEditable(false);

        jTextFieldCodigoCidade.setEditable(false);

        jTextFieldNomeCidade.setEditable(false);

        javax.swing.GroupLayout jPanelDadosAlunoLayout = new javax.swing.GroupLayout(jPanelDadosAluno);
        jPanelDadosAluno.setLayout(jPanelDadosAlunoLayout);
        jPanelDadosAlunoLayout.setHorizontalGroup(
            jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosAlunoLayout.createSequentialGroup()
                        .addComponent(jTextFieldCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosAlunoLayout.createSequentialGroup()
                        .addGroup(jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDadosAlunoLayout.createSequentialGroup()
                                .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldContato))
                            .addGroup(jPanelDadosAlunoLayout.createSequentialGroup()
                                .addComponent(jTextFieldCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadosAlunoLayout.setVerticalGroup(
            jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDadosAluno;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCodigoAluno;
    private javax.swing.JTextField jTextFieldCodigoCidade;
    private javax.swing.JTextField jTextFieldContato;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldNomeCidade;
    // End of variables declaration//GEN-END:variables
}
